//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactos
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Cedula { get; set; }
        public string Foto { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Sexo { get; set; }
        public string Edad { get; set; }
        public Nullable<System.DateTime> FNacimiento { get; set; }
        public string Afiliados { get; set; }
        public string MembresiaD { get; set; }
        public string TrabajoL { get; set; }
        public string DireccionOfi { get; set; }
        public string TelOficina { get; set; }
        public Nullable<bool> EstadoMenbresia { get; set; }
        public Nullable<System.DateTime> FIngreso { get; set; }
        public Nullable<System.DateTime> FSalida { get; set; }
    }
}
